name: Deploy FastAPI Blog

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      # These should be set in your GitHub repository secrets
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install python-multipart  # required for Form(...)
      
      # 4. Run database migrations (if using Alembic)
      - name: Run migrations
        run: |
          # Uncomment and configure if you use Alembic
          # alembic upgrade head
          echo "Skipping migrations step. Configure Alembic if needed."

      # 5. Start FastAPI with Uvicorn
      - name: Start FastAPI
        run: |
          uvicorn main:app --host 0.0.0.0 --port 8000
